<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Inv_detail extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Inv_detail_model');
    } 

    /*
     * Listing of inv_details
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('inv_detail/index?');
        $config['total_rows'] = $this->Inv_detail_model->get_all_inv_details_count();
        $this->pagination->initialize($config);

        $data['inv_details'] = $this->Inv_detail_model->get_all_inv_details($params);
        
        $data['_view'] = 'inv_detail/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new inv_detail
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'name' => $this->input->post('name'),
				'user_id' => $this->input->post('user_id'),
				'birth_year' => $this->input->post('birth_year'),
				'api_key' => $this->input->post('api_key'),
				'api_secret' => $this->input->post('api_secret'),
				'code' => $this->input->post('code'),
				'token' => $this->input->post('token'),
				'redirect_url' => $this->input->post('redirect_url'),
				'code_gen_date' => $this->input->post('code_gen_date'),
				'token_gen_dt' => $this->input->post('token_gen_dt'),
				'status' => $this->input->post('status'),
            );
            
            $inv_detail_id = $this->Inv_detail_model->add_inv_detail($params);
            redirect('inv_detail/index');
        }
        else
        {            
            $data['_view'] = 'inv_detail/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a inv_detail
     */
    function edit($inv_id)
    {   
        // check if the inv_detail exists before trying to edit it
        $data['inv_detail'] = $this->Inv_detail_model->get_inv_detail($inv_id);
        
        if(isset($data['inv_detail']['inv_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'name' => $this->input->post('name'),
					'user_id' => $this->input->post('user_id'),
					'birth_year' => $this->input->post('birth_year'),
					'api_key' => $this->input->post('api_key'),
					'api_secret' => $this->input->post('api_secret'),
					'code' => $this->input->post('code'),
					'token' => $this->input->post('token'),
					'redirect_url' => $this->input->post('redirect_url'),
					'code_gen_date' => $this->input->post('code_gen_date'),
					'token_gen_dt' => $this->input->post('token_gen_dt'),
					'status' => $this->input->post('status'),
                );

                $this->Inv_detail_model->update_inv_detail($inv_id,$params);            
                redirect('inv_detail/index');
            }
            else
            {
                $data['_view'] = 'inv_detail/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The inv_detail you are trying to edit does not exist.');
    } 

    /*
     * Deleting inv_detail
     */
    function remove($inv_id)
    {
        $inv_detail = $this->Inv_detail_model->get_inv_detail($inv_id);

        // check if the inv_detail exists before trying to delete it
        if(isset($inv_detail['inv_id']))
        {
            $this->Inv_detail_model->delete_inv_detail($inv_id);
            redirect('inv_detail/index');
        }
        else
            show_error('The inv_detail you are trying to delete does not exist.');
    }
    function test()
    {
        $this->load->library('session');
        $data=$this->input->post('data',TRUE);
        if(!empty($data))
        {
            $id=array();
            $name=array();
            foreach ($data as $key => $value) {
                $value=explode('---', $value);
                $id []= $value[0];

                $name[] = $value[1];
            }
            $this->session->set_userdata('user_ids',$id);
            $this->session->set_userdata('user_names',$name);    
        }
        print_r($this->session->user_ids);
        print_r($this->session->user_names);
    }
    
}
